# Generated by Django 3.2.7 on 2021-09-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(default=True, upload_to='media/'),
        ),
    ]
